FROM node:22-alpine AS builder
WORKDIR /app

# Coolify/CI may pass VITE_* as build args (not committed .env files).
# Expose them to Vite at build time via ENV so `vite build` can read them.
ARG COOLIFY_URL
ARG COOLIFY_FQDN
ARG SERVICE_FQDN_WEB
ARG SERVICE_URL_WEB
ARG VITE_API_BASE_URL
ARG VITE_API_BASE_URL_NO_VERSION
ARG VITE_BACKEND_HOST
ARG VITE_BACKEND_PORT
ARG VITE_BACKEND_PROTOCOL
ARG VITE_COOKIE_DOMAIN
ARG VITE_COOKIE_SAMESITE
ARG VITE_COOKIE_SECURE
ARG VITE_CORS_ALLOWED_ORIGINS
ARG VITE_DEBUG_MODE
ARG VITE_ENABLE_PWA_PREFETCH
ARG VITE_FRONTEND_HOST
ARG VITE_FRONTEND_PORT
ARG VITE_FRONTEND_PROTOCOL
ARG VITE_FRONTEND_URL
ARG VITE_RUNTIME_ENV
ARG VITE_USE_COOKIES

ENV COOLIFY_URL=$COOLIFY_URL \
    COOLIFY_FQDN=$COOLIFY_FQDN \
    SERVICE_FQDN_WEB=$SERVICE_FQDN_WEB \
    SERVICE_URL_WEB=$SERVICE_URL_WEB \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_API_BASE_URL_NO_VERSION=$VITE_API_BASE_URL_NO_VERSION \
    VITE_BACKEND_HOST=$VITE_BACKEND_HOST \
    VITE_BACKEND_PORT=$VITE_BACKEND_PORT \
    VITE_BACKEND_PROTOCOL=$VITE_BACKEND_PROTOCOL \
    VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN \
    VITE_COOKIE_SAMESITE=$VITE_COOKIE_SAMESITE \
    VITE_COOKIE_SECURE=$VITE_COOKIE_SECURE \
    VITE_CORS_ALLOWED_ORIGINS=$VITE_CORS_ALLOWED_ORIGINS \
    VITE_DEBUG_MODE=$VITE_DEBUG_MODE \
    VITE_ENABLE_PWA_PREFETCH=$VITE_ENABLE_PWA_PREFETCH \
    VITE_FRONTEND_HOST=$VITE_FRONTEND_HOST \
    VITE_FRONTEND_PORT=$VITE_FRONTEND_PORT \
    VITE_FRONTEND_PROTOCOL=$VITE_FRONTEND_PROTOCOL \
    VITE_FRONTEND_URL=$VITE_FRONTEND_URL \
    VITE_RUNTIME_ENV=$VITE_RUNTIME_ENV \
    VITE_USE_COOKIES=$VITE_USE_COOKIES

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build

# Etapa final
FROM node:22-alpine
WORKDIR /app

# Instalar "serve" para servir archivos estáticos
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
